name: Quick Test

on: push

jobs:
  default:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt dependencies
      if: ${{ runner.os == 'Linux' }}
      run: |
        install="sudo apt-get install
        -yq --no-install-suggests --no-install-recommends"
        $install build-essential tor xvfb
    - name: Install brew dependencies
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install tor
        brew services start tor
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint
        pip install -r requirements.txt
    - name: Lint
      if: ${{ matrix.os == 'ubuntu-18.04' && matrix.python-version == '3.9' }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 hyperbit --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 hyperbit --count --exit-zero --statistics
        pylint hyperbit --exit-zero
    - name: Install
      run: |
        python setup.py install
    - name: Test
      run: |
        export PYTHONWARNINGS=all
        python -m unittest discover -v -s ./tests
